#!/usr/bin/env bash
# Generate a Kyverno ClusterPolicy that denies the revoked image digests.
#
#   gen-revocation-policy.sh <revocations.json> > kyverno-deny-revoked.yaml
#
# Signature verification cannot express revocation: a revoked image still
# carries a perfectly valid signature. This policy is the second half — apply
# it next to kyverno-verify-images.yaml, and regenerate it whenever the list's
# serial advances.
#
# The output is a static digest list, so it needs no callback to us at
# admission time and works unchanged in air-gapped clusters.
set -euo pipefail

LIST="${1:-}"
if [ -z "$LIST" ] || [ ! -r "$LIST" ]; then
  echo "usage: $0 <revocations.json>" >&2
  exit 2
fi
command -v jq >/dev/null 2>&1 || { echo "ERROR: jq is required" >&2; exit 2; }

schema="$(jq -r '.schema // empty' "$LIST")"
[ "$schema" = "ebpfsentinel.revocations/v1" ] || {
  echo "ERROR: unexpected schema '$schema' (want ebpfsentinel.revocations/v1)" >&2; exit 2; }

serial="$(jq -r '.serial' "$LIST")"
updated="$(jq -r '.updated_at' "$LIST")"

cat <<EOF
# GENERATED by policy/gen-revocation-policy.sh — do not edit by hand.
# Source list serial: ${serial} (updated ${updated})
#
# Denies eBPFsentinel image digests that have been revoked. Apply ALONGSIDE
# kyverno-verify-images.yaml: that policy proves an image is authentic, this
# one blocks the authentic images we have since withdrawn.
#
# It reads the resolved image digest, which kyverno-verify-images.yaml supplies
# via \`mutateDigest: true\` — verifyImages runs in the mutating phase, before
# this validation. Deploying this policy without that one leaves tag-only pod
# specs with no digest to match.
#
# Regenerate whenever the revocation list serial advances. A cluster running a
# stale copy silently keeps admitting withdrawn images; compare the
# ebpfsentinel.io/revocation-serial annotation against the published list.
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: ebpfsentinel-deny-revoked
  annotations:
    policies.kyverno.io/title: Deny revoked eBPFsentinel images
    policies.kyverno.io/category: Supply Chain Security
    policies.kyverno.io/description: >-
      Blocks eBPFsentinel image digests listed in the signed revocation list.
    ebpfsentinel.io/revocation-serial: "${serial}"
    ebpfsentinel.io/revocation-updated: "${updated}"
spec:
  validationFailureAction: Enforce
  background: true
  rules:
    - name: deny-revoked-digests
      match:
        any:
          - resources:
              kinds:
                - Pod
      preconditions:
        any:
          - key: "{{ images.containers.*.digest }}"
            operator: AnyIn
            value:
EOF

# An empty list yields an empty value list, which AnyIn never satisfies — the
# policy stays installed and keeps advertising its serial.
jq -r '[.revocations[] | select(.kind == "image") | .digest] | .[] | "              - \"" + . + "\""' "$LIST"
if [ "$(jq '[.revocations[] | select(.kind == "image")] | length' "$LIST")" -eq 0 ]; then
  echo "              []"
fi

cat <<EOF
      validate:
        message: >-
          This eBPFsentinel image digest has been revoked and must not run.
          Upgrade to a supported release; see the advisory listed below.
        deny: {}
EOF

jq -r '[.revocations[] | select(.kind == "image")]
       | if length == 0 then empty
         else "# revoked digests in this policy:", (.[] | "#   " + .name + "@" + .digest + " (" + .release + ") — " + .reason + " — " + .advisory)
         end' "$LIST"
