#!/usr/bin/env python3
"""Build the one changelog a customer reads, from a release manifest.

    aggregate-changelog.py <releases/<version>.yaml> [--changelog-dir DIR]

Each component keeps its notes in `changelogs/<name>.md`. This lifts the
section matching the version the manifest declares for that component, and
prints the whole release as a single document: what it contains, what it runs
against, what breaks, then every component's notes in order.

Two workflows need this output — the release itself and the signed measurements
that follow it — and a customer comparing the two would rightly wonder which
one to believe if they were generated by two copies of the same logic.

Exit 0 = written, 1 = a component's section is missing.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

import yaml


def section(text: str, version: str) -> str | None:
    """The body under `## [version]`, up to the next `## ` heading."""
    start = re.search(rf"^## \[{re.escape(version)}\].*$", text, re.M)
    if not start:
        return None
    rest = text[start.end() :]
    end = re.search(r"^## ", rest, re.M)
    return (rest[: end.start()] if end else rest).strip()


def demote(body: str) -> str:
    """Push H3-H5 down one level so they nest under the component heading."""
    return re.sub(r"^(#{3,5}) ", r"#\1 ", body, flags=re.M)


def render(doc: dict, changelog_dir: Path) -> tuple[str, list[str]]:
    out: list[str] = []
    missing: list[str] = []
    compat = doc.get("compatibility") or {}

    out.append(f"# eBPFsentinel {doc['release']}")
    out.append("")
    out.append(f"Released {doc['date']} - status: **{doc['status']}**.")
    if doc.get("supersedes"):
        out.append(f"Supersedes {doc['supersedes']}.")
    out.append("")
    out.append("| Component | Version | License |")
    out.append("|---|---|---|")
    for c in doc["components"]:
        out.append(f"| {c['name']} | {c['version']} | {c['license']} |")
    out.append("")
    out.append(
        f"**Requires** kernel {compat.get('kernel_min')}+, "
        f"Kubernetes {compat.get('kubernetes')}."
    )
    if compat.get("notes"):
        out += ["", compat["notes"]]

    for key, title in (("breaking_changes", "Breaking changes"), ("highlights", "Highlights")):
        items = doc.get(key) or []
        if items:
            out += ["", f"## {title}", ""]
            out += [f"- {it}" for it in items]

    out += ["", "## Per-component release notes"]
    for c in doc["components"]:
        name, version = c["name"], str(c["version"])
        out += ["", f"### {name} {version}", ""]
        path = changelog_dir / f"{name}.md"
        body = section(path.read_text(), version) if path.is_file() else None
        if body is None:
            missing.append(name)
            out.append("_No release notes recorded._")
        else:
            out.append(demote(body))

    return "\n".join(out) + "\n", missing


def main() -> int:
    ap = argparse.ArgumentParser(add_help=True)
    ap.add_argument("manifest", type=Path)
    ap.add_argument("--changelog-dir", type=Path, default=None)
    ap.add_argument("-o", "--output", type=Path, default=None, help="default: stdout")
    args = ap.parse_args()

    doc = yaml.safe_load(args.manifest.read_text())
    changelog_dir = args.changelog_dir or args.manifest.resolve().parent.parent / "changelogs"
    text, missing = render(doc, changelog_dir)

    if args.output:
        args.output.write_text(text)
    else:
        sys.stdout.write(text)

    for name in missing:
        print(f"error: {name} has no notes for its declared version", file=sys.stderr)
    return 1 if missing else 0


if __name__ == "__main__":
    sys.exit(main())
